### ISSUE TITLE
[SUGGESTION] Config for F3 menu

### ISSUE THREAD

**Issue by Sunconure11** [joper333/ImmersiveTravelOverhaul#4]
Basically what it says on the tin. There should be an option to have the mod not touch the F3 menu, just in case a player does not want to bother with this mod in say, a pack.

**Comment by joper333** [comment]
I dont see a point in doing this as the mod loses meaning if coordinates are visible in the f3 menu. If this mod is in a modpack and you dont like it you can just take the mod off. and if its integrated into the modpack then I feel like its the vision of the modpack creator to have it be that way. Also I suck at modding so i would have no idea where to even begin with making this suggestion a thing.
