### ISSUE TITLE
Forge Port

### ISSUE THREAD

**Issue by YeahBoi321** [joper333/ImmersiveTravelOverhaul#5]
So, I am a Java beginner, and I want to try and port your mod to forge for 1.18.2. I have already started working on it, I have the sextant in-game, although still working on functionality, and I was wondering, if I am able to get it to your standards, if I could publish it to curseforge once it has been completed. No matter what you say, I will continue, even if I have to keep it for myself, so yeah, just came here to preemptively ask for permission, just so I don't get my hopes up or anything, like if you are already working on a port.

**Comment by joper333** [comment]
I have been working on a port, but its not my priority right now and i havent touched it in a while. When it comes to permissions the mod is under the public domain, you can do whatever you want with it, i have no power to stop you, but it would be nice if i could get some credit and a link to my curseforge page, although it's not required.

**Comment by YeahBoi321** [comment]
Yeah, but even though it is public domain I would prefer to respect the creator's opinion on using their work, especially since I am just getting the models from here.

**Comment by joper333** [comment]
again, you are free to do whatever you wish. i would appreciate a link or a mention of my name wherever you publish it though, but it is not required.
